#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations 
python manage.py makemigrations demo account

python manage.py migrate

#python manage.py runserver 0.0.0.0:8000

python manage.py collectstatic --no-input

gunicorn pressure_sore_with_admin.wsgi:application --workers 3 --timeout 600 --bind 0.0.0.0:9999